apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-test-kb-qa

resources:
- ../../base

images:
- name: image-registry.openshift-image-registry.svc:5000/ocp-test-kb-dev/ocp-testing-kb
  newName: image-registry.openshift-image-registry.svc:5000/ocp-test-kb-qa/ocp-testing-kb
  newTag: "102725.6"
