apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-test-kb-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: ocp-test-kb-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/dev
    repoURL: https://github.com/kevchu3/kevin-testing-argo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      #selfHeal: true
      selfHeal: false