apiVersion: v1
kind: Service
metadata:
  name: ocp-test-kb
spec:
  selector:
    app: ocp-test-kb
  ports:
    #- protocol: TCP
    #  port: 5000
    #  targetPort: 5000
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081